REPO_URL="https://github.com/ymatrix-data/TPC-H"
ADMIN_USER="mxadmin"
INSTALL_DIR="/home/mxadmin/workspace/TPC-H"
EXPLAIN_ANALYZE="true"
RANDOM_DISTRIBUTION="false"
MULTI_USER_COUNT="1"
GEN_DATA_SCALE="100"
SINGLE_USER_ITERATIONS="1"
RUN_COMPILE_TPCH="false"
RUN_GEN_DATA="false"
RUN_INIT="false"
RUN_DDL="false"
RUN_LOAD="false"
RUN_SQL="true"
RUN_SINGLE_USER_REPORT="true"
RUN_MULTI_USER="false"
RUN_MULTI_USER_REPORT="false"
GREENPLUM_PATH="/opt/ymatrix/matrixdb5/greenplum_path.sh"
SMALL_STORAGE="USING mars2" # For region/nation, eg: USING mars2. Empty means heap
MEDIUM_STORAGE="USING mars2 with (compress_threshold=12000)" # For customer/part/partsupp/supplier, eg: with(appendonly=true, orientation=column), USING mars2. Empty means heap
LARGE_STORAGE="USING mars2 with (compress_threshold=12000)" # For lineitem, orders, eg: with(appendonly=true, orientation=column, compresstype=1z4), USING mars2. Empty means heap
OPTIMIZER="off"
GEN_DATA_DIR="${INSTALL_DIR}/generated"
EXT_HOST_DATA_DIR="~"
ADD_FOREIGN_KEY="false"
CREATE_TBL="false"
