REPO_URL="https://github.com/ymatrix-data/TPC-H"
ADMIN_USER="mxadmin"
INSTALL_DIR="/mxdata/TPC-H"
EXPLAIN_ANALYZE="true"
RANDOM_DISTRIBUTION="false"
MULTI_USER_COUNT="1"
GEN_DATA_SCALE="1"
SINGLE_USER_ITERATIONS="1"
RUN_COMPILE_TPCH="true"
RUN_GEN_DATA="true"
RUN_INIT="true"
RUN_DDL="true"
RUN_LOAD="true"
RUN_SQL="true"
RUN_SINGLE_USER_REPORT="true"
RUN_MULTI_USER="false"
RUN_MULTI_USER_REPORT="false"
GREENPLUM_PATH="//usr/local/matrixdb/greenplum_path.sh"
SMALL_STORAGE="USING mars2" # For region/nation, eg: USING mars2. Empty means heap
MEDIUM_STORAGE="USING mars2" # For customer/part/partsupp/supplier, eg: with(appendonly=true, orientation=column), USING mars2. Empty means heap
LARGE_STORAGE="USING mars2" # For lineitem, orders, eg: with(appendonly=true, orientation=column, compresstype=1z4), USING mars2. Empty means heap
OPTIMIZER="off"
GEN_DATA_DIR="/mxdata/TPC-H/generated"
EXT_HOST_DATA_DIR="~"
ADD_FOREIGN_KEY="false"
CREATE_TBL="false"
