CREATE TABLE tpch.nation
(N_NATIONKEY SMALLINT,
N_NAME TEXT :MARS_ENCODING,
N_REGIONKEY SMALLINT,
N_COMMENT TEXT)
:SMALL_STORAGE
:DISTRIBUTED_BY
:CREATE_MARS_BTREE_INDEX;
CREATE INDEX ON tpch.nation USING mars3_brin(N_NAME);
