CREATE TABLE tpch.orders
(O_ORDERKEY BIGINT,
O_CUSTKEY INT,
O_ORDERSTATUS "char" :MARS_ENCODING,
O_TOTALPRICE float8,
O_ORDERDATE DATE :MARS_ENCODING,
O_ORDERPRIORITY TEXT :MARS_ENCODING,
O_CLERK TEXT,
O_SHIPPRIORITY INTEGER,
O_COMMENT TEXT)
:LARGE_STORAGE
:DISTRIBUTED_BY
:CREATE_MARS_BTREE_INDEX
PARTITION BY RANGE (O_ORDERDATE)
(start('1992-01-01') INCLUSIVE end ('1998-12-31') INCLUSIVE every (interval '1 year'),
default partition others);
CREATE INDEX ON tpch.orders USING mars3_brin(O_ORDERSTATUS, O_ORDERDATE, O_ORDERPRIORITY);

