CREATE TABLE tpch.partsupp
(PS_PARTKEY INT,
PS_SUPPKEY INT,
PS_AVAILQTY SMALLINT :MARS_ENCODING,
PS_SUPPLYCOST float8,
PS_COMMENT TEXT)
:MEDIUM_STORAGE
:DISTRIBUTED_BY
:CREATE_MARS_BTREE_INDEX;
CREATE INDEX ON tpch.partsupp USING mars3_brin(PS_AVAILQTY);
