CREATE TABLE tpch.region
(R_REGIONKEY SMALLINT,
R_NAME TEXT :MARS_ENCODING,
R_COMMENT TEXT)
:SMALL_STORAGE
:DISTRIBUTED_BY
:CREATE_MARS_BTREE_INDEX;
CREATE INDEX ON tpch.region USING mars3_brin(R_NAME);
