CREATE TABLE tpch.customer
(C_CUSTKEY INT, 
C_NAME TEXT,
C_ADDRESS TEXT,
C_NATIONKEY SMALLINT,
C_PHONE TEXT,
C_ACCTBAL float8 :MARS2_ENCODING_MINMAX,
C_MKTSEGMENT TEXT :MARS2_ENCODING_MINMAX,
C_COMMENT TEXT)
:MEDIUM_STORAGE
:DISTRIBUTED_BY;
:CREATE_MARS2_BTREE_INDEX;
