CREATE TABLE tpch.lineitem
(L_ORDERKEY BIGINT,
L_PARTKEY INT,
L_SUPPKEY INT,
L_LINENUMBER INTEGER,
L_QUANTITY SMALLINT :MARS2_ENCODING_MINMAX,
L_EXTENDEDPRICE FLOAT8,
L_DISCOUNT FLOAT8, -- low cardinality, but not string
L_TAX FLOAT8, -- low cardinality, but not string
L_RETURNFLAG CHAR :MARS2_ENCODING_MINMAX,
L_LINESTATUS CHAR,
L_SHIPDATE DATE :MARS2_ENCODING_MINMAX,
L_COMMITDATE DATE,
L_RECEIPTDATE DATE :MARS2_ENCODING_MINMAX,
L_SHIPINSTRUCT TEXT :MARS2_ENCODING_MINMAX, -- low cardinality
L_SHIPMODE TEXT :MARS2_ENCODING_MINMAX, -- low cardinality
L_COMMENT TEXT)
:LARGE_STORAGE
:DISTRIBUTED_BY
PARTITION BY RANGE (L_SHIPDATE)
(start('1992-01-01') INCLUSIVE end ('1998-12-31') INCLUSIVE every (30),
default partition others);
:CREATE_MARS2_BTREE_INDEX;
