CREATE TABLE tpch.nation
(N_NATIONKEY SMALLINT, -- tinyint
N_NAME TEXT :MARS2_ENCODING_MINMAX, -- low cardinality
N_REGIONKEY SMALLINT, -- tinyint
N_COMMENT TEXT)
:SMALL_STORAGE
:DISTRIBUTED_BY;
:CREATE_MARS2_BTREE_INDEX;
