CREATE TABLE tpch.part
(P_PARTKEY INT,
P_NAME TEXT :MARS2_ENCODING_MINMAX,
P_MFGR TEXT,
P_BRAND TEXT :MARS2_ENCODING_MINMAX,
P_TYPE TEXT :MARS2_ENCODING_MINMAX,
P_SIZE SMALLINT :MARS2_ENCODING_MINMAX,
P_CONTAINER TEXT :MARS2_ENCODING_MINMAX,
P_RETAILPRICE float8,
P_COMMENT TEXT)
:MEDIUM_STORAGE
:DISTRIBUTED_BY;
:CREATE_MARS2_BTREE_INDEX;
