CREATE TABLE tpch.partsupp
(PS_PARTKEY INT,
PS_SUPPKEY INT,
PS_AVAILQTY SMALLINT :MARS2_ENCODING_MINMAX,
PS_SUPPLYCOST FLOAT8,
PS_COMMENT TEXT)
:MEDIUM_STORAGE
:DISTRIBUTED_BY;
:CREATE_MARS2_BTREE_INDEX;
