CREATE TABLE tpch.region
(R_REGIONKEY SMALLINT,
R_NAME TEXT :MARS3_ENCODING,
R_COMMENT TEXT)
:SMALL_STORAGE
:DISTRIBUTED_BY
:CREATE_MARS3_BTREE_INDEX;
CREATE INDEX ON tpch.region USING mars3_brin(R_NAME);
