CREATE TABLE tpch.SUPPLIER 
(S_SUPPKEY INT,
S_NAME TEXT,
S_ADDRESS TEXT,
S_NATIONKEY SMALLINT, -- tinyint
S_PHONE TEXT,
S_ACCTBAL FLOAT8,
S_COMMENT TEXT)
:MEDIUM_STORAGE
:DISTRIBUTED_BY;
:CREATE_MARS2_BTREE_INDEX;
